#!/usr/bin/env Rscript

suppressPackageStartupMessages(library(optparse))
suppressPackageStartupMessages(library(rasterVis))

opt.list <- list(
	make_option(c('-b','--band'), type = 'integer', default = 1, metavar = 'INTEGER', help = 'The raster band to plot (default is %default).'),
	make_option(c('-x','--xsize'), type = 'integer', metavar = 'INTEGER', help = 'Size in inches of the plotting window in the X direction (i.e., width).'),
	make_option(c('-y','--ysize'), type = 'integer', metavar = 'INTEGER', help = 'Size in inches of the plotting window in the Y direction (i.e., height).')
)

opt.parser <- OptionParser(option_list = opt.list,
						   usage = 'usage: %prog <raster>\n',
						   description = 'Quickly display a map of raster file from the command line.\n\nArguments:\n\t<raster>\n\t\tRaster file path.')

arguments <- parse_args(opt.parser, positional_arguments = 1)
pos.args <- arguments$args
opt.args <- arguments$options

f <- pos.args[1]
b <- opt.args$band
w <- opt.args$xsize
h <- opt.args$ysize

r <- raster(f, band = b)
nrow <- nrow(r)
ncol <- ncol(r)

if (is.null(w) & is.null(h)) {
	w <- 9
	h <- nrow * (w / ncol)
} else if (is.null(w) & !is.null(h)) {
	w <- ncol * (h / nrow)
} else if (!is.null(w) & is.null(h)) {
	h <- nrow * (w / ncol)
}

c <- colorRampPalette(c('#0000AA','#0055FF','#00AAFF','#55FFFF','#AAFFAA','#FFFF55','#FFAA00','#FF5500','#AA0000'))
n <- basename(f)

X11(width = w, height = h)
levelplot(r, margin = F, col.regions = 	c, main = n)
message('Press return to close map...')
invisible(readLines('stdin', n = 1))